---
all:
  hosts:
    control:
      ansible_host: control
      ansible_user: rhel
      ansible_password: ansible123!

    rhel01:
      ansible_host: rhel01
      ansible_user: rhel
      ansible_password: ansible123!

  children:
    appservers:
      hosts:
        rhel01:
