---
# ansible.controller is pre-installed on AAP nodes, no need to install it
collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=8.0.0"
  - name: containers.podman
    version: ">=1.12.0"
